resources:
  - name: EXT_S_SYC_AU_0025_fileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "pipelines_1619190832/test.txt"
pipelines:
  - name: EXT_S_SYC_AU_0025
    steps:
      - name: EXT_S_SYC_AU_0025
        type: UploadArtifact
        syntaxVersion: 1.0.0
        configuration:
          targetPath: "pipelines_1619190832/EXT_S_SYC_AU_0025"
          integrations:
            - name: s_artifactory
          inputResources:
            - name: EXT_S_SYC_AU_0025_fileSpec
