resources:
  - name: TEST_fileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local/TEST_fileSpec.txt"

pipelines:
  - name: pipeline_TEST
    steps:
      - name: TEST
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          outputResources:
            - name: TEST_fileSpec
        execution:
          onExecute:
            - echo "${run_id}" > TEST_fileSpec.txt
            - jfrog rt upload TEST_fileSpec.txt test-automation-generic-local --detailed-summary=true
